// Country rooms — every country, grouped by continent for the picker
export const COUNTRY_ROOMS = [
  // Africa
  {flag:"🇿🇼",country:"Zimbabwean",name:"Zimbabwe",continent:"Africa"},
  {flag:"🇳🇬",country:"Nigerian",name:"Nigeria",continent:"Africa"},
  {flag:"🇨🇲",country:"Cameroonian",name:"Cameroon",continent:"Africa"},
  {flag:"🇨🇩",country:"Congolese (DRC)",name:"DR Congo",continent:"Africa"},
  {flag:"🇨🇬",country:"Congolese (ROC)",name:"Congo",continent:"Africa"},
  {flag:"🇨🇮",country:"Ivorian",name:"Ivory Coast",continent:"Africa"},
  {flag:"🇸🇳",country:"Senegalese",name:"Senegal",continent:"Africa"},
  {flag:"🇲🇱",country:"Malian",name:"Mali",continent:"Africa"},
  {flag:"🇧🇫",country:"Burkinabe",name:"Burkina Faso",continent:"Africa"},
  {flag:"🇬🇳",country:"Guinean",name:"Guinea",continent:"Africa"},
  {flag:"🇬🇭",country:"Ghanaian",name:"Ghana",continent:"Africa"},
  {flag:"🇰🇪",country:"Kenyan",name:"Kenya",continent:"Africa"},
  {flag:"🇪🇹",country:"Ethiopian",name:"Ethiopia",continent:"Africa"},
  {flag:"🇿🇦",country:"South African",name:"South Africa",continent:"Africa"},
  {flag:"🇲🇿",country:"Mozambican",name:"Mozambique",continent:"Africa"},
  {flag:"🇿🇲",country:"Zambian",name:"Zambia",continent:"Africa"},
  {flag:"🇹🇿",country:"Tanzanian",name:"Tanzania",continent:"Africa"},
  {flag:"🇺🇬",country:"Ugandan",name:"Uganda",continent:"Africa"},
  {flag:"🇷🇼",country:"Rwandan",name:"Rwanda",continent:"Africa"},
  {flag:"🇹🇬",country:"Togolese",name:"Togo",continent:"Africa"},
  {flag:"🇧🇯",country:"Beninese",name:"Benin",continent:"Africa"},
  {flag:"🇳🇪",country:"Nigerien",name:"Niger",continent:"Africa"},
  {flag:"🇹🇩",country:"Chadian",name:"Chad",continent:"Africa"},
  {flag:"🇸🇩",country:"Sudanese",name:"Sudan",continent:"Africa"},
  {flag:"🇱🇾",country:"Libyan",name:"Libya",continent:"Africa"},
  {flag:"🇲🇦",country:"Moroccan",name:"Morocco",continent:"Africa"},
  {flag:"🇹🇳",country:"Tunisian",name:"Tunisia",continent:"Africa"},
  {flag:"🇲🇷",country:"Mauritanian",name:"Mauritania",continent:"Africa"},
  {flag:"🇳🇦",country:"Namibian",name:"Namibia",continent:"Africa"},
  {flag:"🇧🇼",country:"Botswanan",name:"Botswana",continent:"Africa"},
  {flag:"🇦🇴",country:"Angolan",name:"Angola",continent:"Africa"},
  {flag:"🇸🇱",country:"Sierra Leonean",name:"Sierra Leone",continent:"Africa"},
  {flag:"🇱🇷",country:"Liberian",name:"Liberia",continent:"Africa"},
  {flag:"🇬🇲",country:"Gambian",name:"Gambia",continent:"Africa"},
  {flag:"🇲🇼",country:"Malawian",name:"Malawi",continent:"Africa"},
  {flag:"🇩🇿",country:"Algerian",name:"Algeria",continent:"Africa"},
  {flag:"🇪🇬",country:"Egyptian",name:"Egypt",continent:"Africa"},
  {flag:"🇸🇴",country:"Somali",name:"Somalia",continent:"Africa"},
  {flag:"🇧🇮",country:"Burundian",name:"Burundi",continent:"Africa"},
  {flag:"🇸🇸",country:"South Sudanese",name:"South Sudan",continent:"Africa"},
  {flag:"🇬🇦",country:"Gabonese",name:"Gabon",continent:"Africa"},
  {flag:"🇪🇷",country:"Eritrean",name:"Eritrea",continent:"Africa"},
  {flag:"🇱🇸",country:"Basotho",name:"Lesotho",continent:"Africa"},
  {flag:"🇸🇿",country:"Swazi",name:"Eswatini",continent:"Africa"},
  // Europe
  {flag:"🇫🇷",country:"French",name:"France",continent:"Europe"},
  {flag:"🇩🇪",country:"German",name:"Germany",continent:"Europe"},
  {flag:"🇬🇧",country:"British",name:"United Kingdom",continent:"Europe"},
  {flag:"🇮🇹",country:"Italian",name:"Italy",continent:"Europe"},
  {flag:"🇪🇸",country:"Spanish",name:"Spain",continent:"Europe"},
  {flag:"🇵🇹",country:"Portuguese",name:"Portugal",continent:"Europe"},
  {flag:"🇳🇱",country:"Dutch",name:"Netherlands",continent:"Europe"},
  {flag:"🇧🇪",country:"Belgian",name:"Belgium",continent:"Europe"},
  {flag:"🇨🇭",country:"Swiss",name:"Switzerland",continent:"Europe"},
  {flag:"🇸🇪",country:"Swedish",name:"Sweden",continent:"Europe"},
  {flag:"🇳🇴",country:"Norwegian",name:"Norway",continent:"Europe"},
  {flag:"🇵🇱",country:"Polish",name:"Poland",continent:"Europe"},
  {flag:"🇷🇴",country:"Romanian",name:"Romania",continent:"Europe"},
  {flag:"🇺🇦",country:"Ukrainian",name:"Ukraine",continent:"Europe"},
  {flag:"🇷🇺",country:"Russian",name:"Russia",continent:"Europe"},
  {flag:"🇬🇷",country:"Greek",name:"Greece",continent:"Europe"},
  {flag:"🇹🇷",country:"Turkish",name:"Turkey",continent:"Europe"},
  // Asia
  {flag:"🇨🇳",country:"Chinese",name:"China",continent:"Asia"},
  {flag:"🇮🇳",country:"Indian",name:"India",continent:"Asia"},
  {flag:"🇵🇰",country:"Pakistani",name:"Pakistan",continent:"Asia"},
  {flag:"🇧🇩",country:"Bangladeshi",name:"Bangladesh",continent:"Asia"},
  {flag:"🇯🇵",country:"Japanese",name:"Japan",continent:"Asia"},
  {flag:"🇰🇷",country:"South Korean",name:"South Korea",continent:"Asia"},
  {flag:"🇮🇩",country:"Indonesian",name:"Indonesia",continent:"Asia"},
  {flag:"🇵🇭",country:"Filipino",name:"Philippines",continent:"Asia"},
  {flag:"🇻🇳",country:"Vietnamese",name:"Vietnam",continent:"Asia"},
  {flag:"🇹🇭",country:"Thai",name:"Thailand",continent:"Asia"},
  {flag:"🇲🇾",country:"Malaysian",name:"Malaysia",continent:"Asia"},
  {flag:"🇸🇬",country:"Singaporean",name:"Singapore",continent:"Asia"},
  {flag:"🇸🇦",country:"Saudi Arabian",name:"Saudi Arabia",continent:"Asia"},
  {flag:"🇦🇪",country:"Emirati",name:"UAE",continent:"Asia"},
  {flag:"🇮🇱",country:"Israeli",name:"Israel",continent:"Asia"},
  {flag:"🇮🇷",country:"Iranian",name:"Iran",continent:"Asia"},
  {flag:"🇮🇶",country:"Iraqi",name:"Iraq",continent:"Asia"},
  {flag:"🇱🇧",country:"Lebanese",name:"Lebanon",continent:"Asia"},
  {flag:"🇯🇴",country:"Jordanian",name:"Jordan",continent:"Asia"},
  {flag:"🇾🇪",country:"Yemeni",name:"Yemen",continent:"Asia"},
  {flag:"🇦🇫",country:"Afghan",name:"Afghanistan",continent:"Asia"},
  {flag:"🇳🇵",country:"Nepali",name:"Nepal",continent:"Asia"},
  {flag:"🇱🇰",country:"Sri Lankan",name:"Sri Lanka",continent:"Asia"},
  // Americas
  {flag:"🇺🇸",country:"American",name:"United States",continent:"Americas"},
  {flag:"🇨🇦",country:"Canadian",name:"Canada",continent:"Americas"},
  {flag:"🇧🇷",country:"Brazilian",name:"Brazil",continent:"Americas"},
  {flag:"🇲🇽",country:"Mexican",name:"Mexico",continent:"Americas"},
  {flag:"🇦🇷",country:"Argentinian",name:"Argentina",continent:"Americas"},
  {flag:"🇨🇴",country:"Colombian",name:"Colombia",continent:"Americas"},
  {flag:"🇵🇪",country:"Peruvian",name:"Peru",continent:"Americas"},
  {flag:"🇨🇱",country:"Chilean",name:"Chile",continent:"Americas"},
  {flag:"🇻🇪",country:"Venezuelan",name:"Venezuela",continent:"Americas"},
  {flag:"🇭🇹",country:"Haitian",name:"Haiti",continent:"Americas"},
  {flag:"🇯🇲",country:"Jamaican",name:"Jamaica",continent:"Americas"},
  {flag:"🇨🇺",country:"Cuban",name:"Cuba",continent:"Americas"},
  // Oceania
  {flag:"🇦🇺",country:"Australian",name:"Australia",continent:"Oceania"},
  {flag:"🇳🇿",country:"New Zealander",name:"New Zealand",continent:"Oceania"},
  {flag:"🇵🇬",country:"Papua New Guinean",name:"Papua New Guinea",continent:"Oceania"},
  {flag:"🇫🇯",country:"Fijian",name:"Fiji",continent:"Oceania"},
];

export const NATIONALITIES = COUNTRY_ROOMS.map(r => r.country).sort();

export const CONTINENTS = ["Africa","Europe","Asia","Americas","Oceania"];

export const INTEREST_ROOMS = [
  {id:"general",name:"🌍 General",desc:"Everyone welcome",type:"public",color:"#10B981"},
  {id:"announcements",name:"📢 Announcements",desc:"Official notices",type:"readonly",color:"#8B5CF6"},
  {id:"emergency",name:"🚨 Emergency Board",desc:"Urgent community notices",type:"readonly",color:"#EF4444"},
  {id:"transfers",name:"💸 Transfer Talk",desc:"Money transfer discussions",type:"public",color:"#F59E0B"},
  {id:"jobs",name:"💼 Jobs & Careers",desc:"Job opportunities",type:"public",color:"#3B82F6"},
  {id:"medicine",name:"🏥 Medicine",desc:"Medical students",type:"public",color:"#EC4899"},
  {id:"technology",name:"💻 Technology",desc:"Tech & engineering",type:"public",color:"#06B6D4"},
  {id:"cybersecurity",name:"🔐 Cybersecurity",desc:"Security professionals",type:"public",color:"#6366F1"},
  {id:"christian",name:"✝️ Christian Fellowship",desc:"Faith community",type:"public",color:"#F59E0B"},
  {id:"muslim",name:"☪️ Muslim Community",desc:"Faith community",type:"public",color:"#10B981"},
  {id:"social",name:"🎉 Social Life",desc:"Events & social",type:"public",color:"#EC4899"},
  {id:"zim_developers",name:"👨‍💻 Zim Developers",desc:"Zimbabwe tech community",type:"public",color:"#3B82F6"},
  {id:"alumni",name:"🎓 Alumni Network",desc:"Graduated members",type:"public",color:"#8B5CF6"},
  {id:"oran",name:"🏙️ Oran City",desc:"Students in Oran",type:"public",city:"Oran",color:"#06B6D4"},
  {id:"alger",name:"🏙️ Alger City",desc:"Students in Alger",type:"public",city:"Alger",color:"#06B6D4"},
  {id:"constantine",name:"🏙️ Constantine City",desc:"Students in Constantine",type:"public",city:"Constantine",color:"#06B6D4"},
];
