compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = "dist"

[[routes]]
pattern = "/.netlify/functions/*"
zone_name = "diaspora-chats.pages.dev"

[env.production]
vars = { GROQ_API_KEY = "YOUR_GROQ_API_KEY" }

[env.development]  
vars = { GROQ_API_KEY = "YOUR_GROQ_API_KEY" }
